version: "3.9"

services:
  db:
    image: postgres:16.1
    container_name: rinha-db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./postgres.conf:/etc/postgresql.conf
    network_mode: host
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 20s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "170MB"

  api1: &api
#    image: h-ssiqueira/rinhabackend2024q1:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    environment:
      - POSTGRESQL_HOST=127.0.0.1
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin
      - SERVER_PORT=8081
    network_mode: host
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "170MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - POSTGRESQL_HOST=127.0.0.1
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin
      - SERVER_PORT=8082
    network_mode: host
    ports:
      - "8082:8082"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
